/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bingo;

import bingo.network.ClientManager;
import bingo.responses.StartGameResponse;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import models.User;

/**
 *
 * @author valmir
 */
public class SalaDeEspera extends javax.swing.JFrame implements Tela {
    
    private ClientManager clientManager;
    private DefaultListModel usersModel = new DefaultListModel();
    /**
     * Creates new form WaitingRoom
     */
    public SalaDeEspera(ClientManager clientManager) {
        this.clientManager = clientManager;
        initComponents();
        LIST_UsersInRoom.setModel(usersModel);
    }
    
    private void clearListUsers() {
        this.usersModel.clear();
    } 
    
    public void updateListUsers(ArrayList<User> users) {
        this.clearListUsers();
        
        for(User u: users) {
            this.usersModel.addElement(u);
        }    
    }
    
    @Override
    public void showGenericError() {
        JOptionPane.showMessageDialog(null, "Algo muito errado deu errado!");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BTN_StartGame = new javax.swing.JButton();
        BTN_ExitRoom = new javax.swing.JButton();
        PN_LSTJgd = new javax.swing.JScrollPane();
        LIST_UsersInRoom = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sala de Espera");

        jLabel1.setText("Usuários na Sala");

        BTN_StartGame.setText("Começar o Jogo");
        BTN_StartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_StartGameActionPerformed(evt);
            }
        });

        BTN_ExitRoom.setText("Sair da Sala");

        PN_LSTJgd.setViewportView(LIST_UsersInRoom);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PN_LSTJgd)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_ExitRoom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 328, Short.MAX_VALUE)
                        .addComponent(BTN_StartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(PN_LSTJgd, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_StartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_ExitRoom))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_StartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_StartGameActionPerformed
        // TODO add your handling code here:
        clientManager.sendMessage(new StartGameResponse());
    }//GEN-LAST:event_BTN_StartGameActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_ExitRoom;
    private javax.swing.JButton BTN_StartGame;
    private javax.swing.JList<String> LIST_UsersInRoom;
    private javax.swing.JScrollPane PN_LSTJgd;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
