/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bingo;

import bingo.network.ClientManager;
import bingo.responses.AssignUserRoomResponse;
import bingo.responses.CreateRoomResponse;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import models.Room;
import models.User;

/**
 *
 * @author 14023691
 */
public class TelaSalas extends bingo.MyJFrame implements Tela {

    private String ra;
    private ArrayList<Room> rooms;
    private ClientManager clientManager;
    private DefaultListModel roomsModel = new DefaultListModel();
    private DefaultListModel usersModel = new DefaultListModel();

    public TelaSalas(ClientManager clientManager, String ra) {
        initComponents();
        this.ra = ra;
        this.setTitle(ra);
        this.clientManager = clientManager;

        LIST_Rooms.setModel(roomsModel);
    }

    private void clearAvailableRooms() {
        roomsModel.removeAllElements();
    }
    private void clearUsersInRoom() {
        usersModel.removeAllElements();
    }

    public void addItensToAvailableRooms(ArrayList<Room> rooms) {
        this.clearAvailableRooms();
        this.rooms = rooms;
        for(Room r : rooms) {
            roomsModel.addElement(r);
        }
    }

    public void showRoomIsFull() {
        JOptionPane.showMessageDialog(null, "Está sala está cheia, tente novamente em outra sala ou crie uma sala!");
    }

    @Override
    public void showGenericError() {
        JOptionPane.showMessageDialog(null, "Algo muito errado deu errado!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PN_LSTSala = new javax.swing.JScrollPane();
        LIST_Users = new javax.swing.JList<>();
        PN_LSTJgd = new javax.swing.JScrollPane();
        LIST_Rooms = new javax.swing.JList<>();
        LBL_Salas = new javax.swing.JLabel();
        LBL_Jgd = new javax.swing.JLabel();
        BUT_AssignToRoom = new bingo.ButtonWithLoader();
        BTN_CreateRoom = new bingo.ButtonWithLoader();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LIST_Users.setEnabled(false);
        LIST_Users.setSelectedIndex(0);
        PN_LSTSala.setViewportView(LIST_Users);

        LIST_Rooms.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        LIST_Rooms.setSelectedIndex(0);
        LIST_Rooms.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                LIST_RoomsValueChanged(evt);
            }
        });
        PN_LSTJgd.setViewportView(LIST_Rooms);

        LBL_Salas.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LBL_Salas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBL_Salas.setText("Salas Disponíveis");
        LBL_Salas.setToolTipText("");

        LBL_Jgd.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        LBL_Jgd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBL_Jgd.setText("Jogadores em Sala");

        BUT_AssignToRoom.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BUT_AssignToRoom.setText("Entrar na Sala");
        BUT_AssignToRoom.setToolTipText("");
        BUT_AssignToRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUT_AssignToRoomActionPerformed(evt);
            }
        });

        BTN_CreateRoom.setLabel("Criar Nova Sala");
        BTN_CreateRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CreateRoomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PN_LSTSala)
                        .addComponent(PN_LSTJgd)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BTN_CreateRoom)
                            .addGap(188, 188, 188)
                            .addComponent(BUT_AssignToRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)))
                    .addComponent(LBL_Jgd)
                    .addComponent(LBL_Salas))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LBL_Salas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PN_LSTJgd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBL_Jgd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PN_LSTSala, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BUT_AssignToRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(BTN_CreateRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LIST_RoomsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_LIST_RoomsValueChanged
        this.clearUsersInRoom();
        Room room =  (Room) roomsModel.get(LIST_Rooms.getSelectedIndex());
        ArrayList<User> users = room.getUsers();
        for(User u : users) {
            this.usersModel.addElement(u);
        }
        LIST_Users.setModel(usersModel);
    }//GEN-LAST:event_LIST_RoomsValueChanged

    private void BTN_CreateRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CreateRoomActionPerformed
        CreateRoomResponse createRequest = new CreateRoomResponse();
        this.clientManager.sendMessage(createRequest);
        BTN_CreateRoom.showLoader();
    }//GEN-LAST:event_BTN_CreateRoomActionPerformed

    private void BUT_AssignToRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUT_AssignToRoomActionPerformed
        int idSala = ((Room)this.roomsModel.get(LIST_Rooms.getSelectedIndex())).getId();
        AssignUserRoomResponse assignResponse = new AssignUserRoomResponse(idSala);
        this.clientManager.sendMessage(assignResponse);
        BUT_AssignToRoom.showLoader();
    }//GEN-LAST:event_BUT_AssignToRoomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private bingo.ButtonWithLoader BTN_CreateRoom;
    private bingo.ButtonWithLoader BUT_AssignToRoom;
    private javax.swing.JLabel LBL_Jgd;
    private javax.swing.JLabel LBL_Salas;
    private javax.swing.JList<String> LIST_Rooms;
    private javax.swing.JList<String> LIST_Users;
    private javax.swing.JScrollPane PN_LSTJgd;
    private javax.swing.JScrollPane PN_LSTSala;
    // End of variables declaration//GEN-END:variables
}
