BEGIN;

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 0, 11, 0)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 1, 1, 0)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 2, 15, 0)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 3, 14, 0)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 4, 3, 0) 

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 0, 23, 0)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 1, 19, 0)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 2, 16, 0) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 3, 27, 0) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 4, 20, 0)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 0, 42, 0)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 1, 39, 0) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 2, NULL, 0) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 3, 31, 0)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 4, 45, 0)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 0, 50, 0)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 1, 47, 0)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 2, 58, 0) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 3, 60, 0) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 4, 55, 0)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 0, 63, 0)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 1, 62, 0)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 2, 74, 0) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 3, 72, 0) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 4, 68, 0)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 0, 12, 1)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 1, 3, 1)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 2, 15, 1)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 3, 14, 1)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 4, 3, 1) 

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 0, 22, 1)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 1, 16, 1)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 2, 21, 1) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 3, 27, 1) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 4, 20, 1)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 0, 40, 1)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 1, 31, 1) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 2, NULL, 1) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 3, 35, 1)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 4, 45, 1)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 0, 46, 1)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 1, 47, 1)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 2, 58, 1) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 3, 59, 1) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 4, 55, 1)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 0, 61, 1)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 1, 69, 1)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 2, 70, 1) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 3, 68, 1) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 4, 63, 1)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 0, 2, 2)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 1, 11, 2)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 2, 10, 2)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 3, 7, 2)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 4, 3, 2) 

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 0, 23, 2)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 1, 18, 2)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 2, 20, 2) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 3, 25, 2) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 4, 29, 2)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 0, 42, 2)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 1, 38, 2) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 2, NULL, 2) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 3, 43, 2)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 4, 45, 2)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 0, 46, 2)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 1, 47, 2)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 2, 58, 2) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 3, 61, 2) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 4, 56, 2)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 0, 69, 2)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 1, 67, 2)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 2, 73, 2) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 3, 62, 2) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 4, 74, 2)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 0, 12, 3)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 1, 2, 3)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 2, 13, 3)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 3, 15, 3)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 4, 3, 3) 

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 0, 20, 3)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 1, 19, 3)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 2, 16, 3) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 3, 26, 3) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 4, 23, 3)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 0, 37, 3)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 1, 39, 3) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 2, NULL, 3) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 3, 42, 3)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 4, 44, 3)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 0, 51, 3)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 1, 42, 3)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 2, 58, 3) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 3, 59, 3) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 4, 54, 3)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 0, 61, 3)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 1, 64, 3)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 2, 70, 3) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 3, 72, 3) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 4, 68, 3)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 0, 13, 4)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 1, 15, 4)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 2, 9, 4)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 3, 4, 4)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 4, 3, 4) 

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 0, 17, 4)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 1, 19, 4)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 2, 30, 4) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 3, 27, 4) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 4, 25, 4)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 0, 34, 4)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 1, 45, 4) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 2, NULL, 4) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 3, 32, 4)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 4, 31, 4)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 0, 58, 4)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 1, 43, 4)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 2, 50, 4) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 3, 46, 4) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 4, 45, 4)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 0, 63, 4)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 1, 68, 4)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 2, 70, 4) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 3, 75, 4) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 4, 62, 4)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 0, 7, 5)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 1, 12, 5)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 2, 2, 5)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 3, 5, 5)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 4, 10, 5) 

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 0, 17, 5)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 1, 19, 5)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 2, 25, 5) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 3, 28, 5) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 4, 27, 5)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 0, 33, 5)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 1, 40, 5) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 2, NULL, 5) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 3, 38, 5)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 4, 43, 5)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 0, 58, 5)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 1, 41, 5)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 2, 57, 5) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 3, 48, 5) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 4, 47, 5)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 0, 61, 5)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 1, 65, 5)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 2, 71, 5) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 3, 75, 5) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 4, 62, 5)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 0, 14, 6)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 1, 13, 6)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 2, 4, 6)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 3, 7, 6)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 4, 8, 6) 

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 0, 22, 6)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 1, 16, 6)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 2, 19, 6) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 3, 27, 6) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 4, 25, 6)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 0, 33, 6)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 1, 44, 6) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 2, NULL, 6) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 3, 42, 6)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 4, 38, 6)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 0, 46, 6)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 1, 43, 6)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 2, 58, 6) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 3, 57, 6) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 4, 49, 6)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 0, 74, 6)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 1, 68, 6)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 2, 70, 6) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 3, 62, 6) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 4, 61, 6)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 0, 1, 7)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 1, 2, 7)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 2, 3, 7)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 3, 15, 7)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 4, 8, 7) 

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 0, 17, 7)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 1, 23, 7)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 2, 27, 7) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 3, 18, 7) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 4, 25, 7)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 0, 34, 7)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 1, 36, 7) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 2, NULL, 7) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 3, 40, 7)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 4, 39, 7)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 0, 58, 7)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 1, 47, 7)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 2, 50, 7) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 3, 46, 7) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 4, 54, 7)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 0, 63, 7)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 1, 61, 7)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 2, 70, 7) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 3, 67, 7) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 4, 62, 7)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 0, 14, 8)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 1, 12, 8)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 2, 10, 8)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 3, 15, 8)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 4, 4, 8) 

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 0, 28, 8)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 1, 23, 8)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 2, 22, 8) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 3, 29, 8) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 4, 25, 8)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 0, 31, 8)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 1, 38, 8) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 2, NULL, 8) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 3, 41, 8)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 4, 39, 8)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 0, 55, 8)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 1, 46, 8)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 2, 50, 8) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 3, 57, 8) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 4, 48, 8)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 0, 62, 8)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 1, 63, 8)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 2, 70, 8) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 3, 72, 8) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 4, 61, 8)


INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 0, 8, 9)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 1, 2, 9)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 2, 15, 9)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 3, 10, 9)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(0, 4, 6, 9) 

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 0, 16, 9)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 1, 20, 9)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 2, 25, 9) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 3, 19, 9) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(1, 4, 27, 9)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 0, 31, 9)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 1, 38, 9) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 2, NULL, 9) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 3, 45, 9)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(2, 4, 39, 9)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 0, 58, 9)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 1, 47, 9)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 2, 59, 9) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 3, 46, 9) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(3, 4, 50, 9)

INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 0, 68, 9)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 1, 73, 9)
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 2, 61, 9) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 3, 70, 9) 
INSERT INTO combinacoes(linha, coluna, valor, nrCartela) VALUES(4, 4, 62, 9)

COMMIT;

